name: Build, Test and Deploy

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  release:
    types: [published]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    env: 
      NUGET_SOURCE: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
      
    permissions:
      packages: write
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '5.0'
          source-url: ${{ env.NUGET_SOURCE }}
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v4.2.0
        with:
          versionSpec: '6.4.x'
      
      - name: GitVersion
        id: version_step # step id used as a reference for output values
        uses: gittools/actions/gitversion/execute@v4.2.0

      - run: dotnet build --restore -p:Version=${{ env.GitVersion_fullSemVer }} -p:PackageId="${{ github.repository_owner }}.GitLabApiClient" -p:PackageProjectUrl="${{ github.repositoryUrl }}" -p:GeneratePackageOnBuild=true -c Release 

      - run: dotnet test --verbosity normal --no-build --no-restore

      - name: Push to GithubPackages
        if: |
          startsWith(github.event.ref, 'refs/tags/')
          || endsWith(github.event.ref, '/master')
          || github.event.action == 'published'
        shell: pwsh
        run: dotnet nuget push **/*.nupkg --source $Env:SOURCE --skip-duplicate
        env:
          SOURCE: ${{ env.NUGET_SOURCE }}

      # Get a short-lived NuGet API key
      - name: NuGet login (OIDC â†’ temp API key)
        if: github.event_name == 'release' && github.event.action == 'published'
        uses: NuGet/login@v1
        id: loginNugetOrg
        with:
          user: ${{ secrets.NUGET_USER }}
    
      # Push the package
      - name: NuGet push
        if: github.event_name == 'release' && github.event.action == 'published'
        run: dotnet nuget push **/*.nupkg --api-key "${{ steps.loginNugetOrg.outputs.NUGET_API_KEY }}" --source https://www.nuget.org/api/v2/package --skip-duplicate
